cohort_folder:
    - 2_obesity_clinic
samples:
    - 2_obesity_clinic/100_nobmi_BOC.obesity_clinic
    - 2_obesity_clinic/101_nobmi_IL4RA.obesity_clinic
    - 2_obesity_clinic/102_nobmi_SRC.obesity_clinic
    - 2_obesity_clinic/103_nobmi_IL1ra.obesity_clinic
    - 2_obesity_clinic/104_nobmi_IL6.obesity_clinic
    - 2_obesity_clinic/105_nobmi_TNFRSF10A.obesity_clinic
    - 2_obesity_clinic/106_nobmi_STK4.obesity_clinic
    - 2_obesity_clinic/107_nobmi_IDUA.obesity_clinic
    - 2_obesity_clinic/108_nobmi_TNFRSF11A.obesity_clinic
    - 2_obesity_clinic/109_nobmi_PAR1.obesity_clinic
    - 2_obesity_clinic/10_nobmi_LAP_TGFb1.obesity_clinic
    - 2_obesity_clinic/110_nobmi_TRAILR2.obesity_clinic
    - 2_obesity_clinic/111_nobmi_PRSS27.obesity_clinic
    - 2_obesity_clinic/112_nobmi_TIE2.obesity_clinic
    - 2_obesity_clinic/113_nobmi_TF.obesity_clinic
    - 2_obesity_clinic/114_nobmi_IL1RL2.obesity_clinic
    - 2_obesity_clinic/115_nobmi_PDGF_subunit_B.obesity_clinic
    - 2_obesity_clinic/116_nobmi_IL27.obesity_clinic
    - 2_obesity_clinic/117_nobmi_IL17D.obesity_clinic
    - 2_obesity_clinic/118_nobmi_CXCL1.obesity_clinic
    - 2_obesity_clinic/119_nobmi_LOX1.obesity_clinic
    - 2_obesity_clinic/11_nobmi_uPA.obesity_clinic
    - 2_obesity_clinic/120_nobmi_Gal9.obesity_clinic
    - 2_obesity_clinic/121_nobmi_GIF.obesity_clinic
    - 2_obesity_clinic/122_nobmi_SCF.obesity_clinic
    - 2_obesity_clinic/123_nobmi_IL18.obesity_clinic
    - 2_obesity_clinic/124_nobmi_FGF21.obesity_clinic
    - 2_obesity_clinic/125_nobmi_PIgR.obesity_clinic
    - 2_obesity_clinic/126_nobmi_RAGE.obesity_clinic
    - 2_obesity_clinic/127_nobmi_SOD2.obesity_clinic
    - 2_obesity_clinic/128_nobmi_CTRC.obesity_clinic
    - 2_obesity_clinic/129_nobmi_FGF23.obesity_clinic
    - 2_obesity_clinic/12_nobmi_IL6_inf.obesity_clinic
    - 2_obesity_clinic/130_nobmi_SPON2.obesity_clinic
    - 2_obesity_clinic/131_nobmi_GH.obesity_clinic
    - 2_obesity_clinic/132_nobmi_FS.obesity_clinic
    - 2_obesity_clinic/133_nobmi_GLO1.obesity_clinic
    - 2_obesity_clinic/134_nobmi_CD84.obesity_clinic
    - 2_obesity_clinic/135_nobmi_PAPPA.obesity_clinic
    - 2_obesity_clinic/136_nobmi_SERPINA12.obesity_clinic
    - 2_obesity_clinic/137_nobmi_REN.obesity_clinic
    - 2_obesity_clinic/138_nobmi_DECR1.obesity_clinic
    - 2_obesity_clinic/139_nobmi_MERTK.obesity_clinic
    - 2_obesity_clinic/13_nobmi_IL17C.obesity_clinic
    - 2_obesity_clinic/140_nobmi_KIM1.obesity_clinic
    - 2_obesity_clinic/141_nobmi_THBS2.obesity_clinic
    - 2_obesity_clinic/142_nobmi_TM.obesity_clinic
    - 2_obesity_clinic/143_nobmi_VSIG2.obesity_clinic
    - 2_obesity_clinic/144_nobmi_AMBP.obesity_clinic
    - 2_obesity_clinic/145_nobmi_PRELP.obesity_clinic
    - 2_obesity_clinic/146_nobmi_HO1.obesity_clinic
    - 2_obesity_clinic/147_nobmi_XCL1.obesity_clinic
    - 2_obesity_clinic/148_nobmi_IL16.obesity_clinic
    - 2_obesity_clinic/149_nobmi_SORT1.obesity_clinic
    - 2_obesity_clinic/14_nobmi_MCP1.obesity_clinic
    - 2_obesity_clinic/150_nobmi_CEACAM8.obesity_clinic
    - 2_obesity_clinic/151_nobmi_PTX3.obesity_clinic
    - 2_obesity_clinic/152_nobmi_PSGL1.obesity_clinic
    - 2_obesity_clinic/153_nobmi_CCL17.obesity_clinic
    - 2_obesity_clinic/154_nobmi_CCL3.obesity_clinic
    - 2_obesity_clinic/155_nobmi_MMP7.obesity_clinic
    - 2_obesity_clinic/156_nobmi_IgG_Fc_receptor_IIb.obesity_clinic
    - 2_obesity_clinic/157_nobmi_ITGB1BP2.obesity_clinic
    - 2_obesity_clinic/158_nobmi_DCN.obesity_clinic
    - 2_obesity_clinic/159_nobmi_Dkk1.obesity_clinic
    - 2_obesity_clinic/15_nobmi_IL17A.obesity_clinic
    - 2_obesity_clinic/160_nobmi_LPL.obesity_clinic
    - 2_obesity_clinic/161_nobmi_PRSS8.obesity_clinic
    - 2_obesity_clinic/162_nobmi_AGRP.obesity_clinic
    - 2_obesity_clinic/163_nobmi_HBEGF.obesity_clinic
    - 2_obesity_clinic/164_nobmi_GDF2.obesity_clinic
    - 2_obesity_clinic/165_nobmi_FABP2.obesity_clinic
    - 2_obesity_clinic/166_nobmi_THPO.obesity_clinic
    - 2_obesity_clinic/167_nobmi_MARCO.obesity_clinic
    - 2_obesity_clinic/168_nobmi_GT.obesity_clinic
    - 2_obesity_clinic/169_nobmi_BNP.obesity_clinic
    - 2_obesity_clinic/16_nobmi_CXCL11.obesity_clinic
    - 2_obesity_clinic/170_nobmi_MMP12.obesity_clinic
    - 2_obesity_clinic/171_nobmi_ACE2.obesity_clinic
    - 2_obesity_clinic/172_nobmi_PDL2.obesity_clinic
    - 2_obesity_clinic/173_nobmi_CTSL1.obesity_clinic
    - 2_obesity_clinic/174_nobmi_hOSCAR.obesity_clinic
    - 2_obesity_clinic/175_nobmi_TNFRSF13B.obesity_clinic
    - 2_obesity_clinic/176_nobmi_TGM2.obesity_clinic
    - 2_obesity_clinic/177_nobmi_LEP.obesity_clinic
    - 2_obesity_clinic/178_nobmi_CA5A.obesity_clinic
    - 2_obesity_clinic/179_nobmi_HSP_27.obesity_clinic
    - 2_obesity_clinic/17_nobmi_AXIN1.obesity_clinic
    - 2_obesity_clinic/180_nobmi_CD4.obesity_clinic
    - 2_obesity_clinic/181_nobmi_NEMO.obesity_clinic
    - 2_obesity_clinic/182_nobmi_VEGFD.obesity_clinic
    - 2_obesity_clinic/183_nobmi_PARP1.obesity_clinic
    - 2_obesity_clinic/184_nobmi_HAOX1.obesity_clinic
    - 2_obesity_clinic/18_nobmi_TRAIL.obesity_clinic
    - 2_obesity_clinic/19_nobmi_IL20RA.obesity_clinic
    - 2_obesity_clinic/1_nobmi_IL8.obesity_clinic
    - 2_obesity_clinic/20_nobmi_CXCL9.obesity_clinic
    - 2_obesity_clinic/21_nobmi_CST5.obesity_clinic
    - 2_obesity_clinic/22_nobmi_IL2RB.obesity_clinic
    - 2_obesity_clinic/23_nobmi_IL1_a.obesity_clinic
    - 2_obesity_clinic/24_nobmi_OSM.obesity_clinic
    - 2_obesity_clinic/25_nobmi_IL2.obesity_clinic
    - 2_obesity_clinic/26_nobmi_CXCL1_inf.obesity_clinic
    - 2_obesity_clinic/27_nobmi_TSLP.obesity_clinic
    - 2_obesity_clinic/28_nobmi_CCL4.obesity_clinic
    - 2_obesity_clinic/29_nobmi_CD6.obesity_clinic
    - 2_obesity_clinic/2_nobmi_VEGFA.obesity_clinic
    - 2_obesity_clinic/30_nobmi_SCF_inf.obesity_clinic
    - 2_obesity_clinic/31_nobmi_IL18_inf.obesity_clinic
    - 2_obesity_clinic/32_nobmi_SLAMF1.obesity_clinic
    - 2_obesity_clinic/33_nobmi_TGFa.obesity_clinic
    - 2_obesity_clinic/34_nobmi_MCP4.obesity_clinic
    - 2_obesity_clinic/35_nobmi_CCL11.obesity_clinic
    - 2_obesity_clinic/36_nobmi_TNFSF14.obesity_clinic
    - 2_obesity_clinic/37_nobmi_FGF23_inf.obesity_clinic
    - 2_obesity_clinic/38_nobmi_IL10RA.obesity_clinic
    - 2_obesity_clinic/39_nobmi_FGF5.obesity_clinic
    - 2_obesity_clinic/3_nobmi_CD8A.obesity_clinic
    - 2_obesity_clinic/40_nobmi_MMP1.obesity_clinic
    - 2_obesity_clinic/41_nobmi_LIFR.obesity_clinic
    - 2_obesity_clinic/42_nobmi_FGF21_inf.obesity_clinic
    - 2_obesity_clinic/43_nobmi_CCL19.obesity_clinic
    - 2_obesity_clinic/44_nobmi_IL15RA.obesity_clinic
    - 2_obesity_clinic/45_nobmi_IL10RB.obesity_clinic
    - 2_obesity_clinic/46_nobmi_IL22_RA1.obesity_clinic
    - 2_obesity_clinic/47_nobmi_IL18R1.obesity_clinic
    - 2_obesity_clinic/48_nobmi_PDL1.obesity_clinic
    - 2_obesity_clinic/49_nobmi_BetaNGF.obesity_clinic
    - 2_obesity_clinic/4_nobmi_MCP3.obesity_clinic
    - 2_obesity_clinic/50_nobmi_CXCL5.obesity_clinic
    - 2_obesity_clinic/51_nobmi_TRANCE.obesity_clinic
    - 2_obesity_clinic/52_nobmi_HGF.obesity_clinic
    - 2_obesity_clinic/53_nobmi_IL12B.obesity_clinic
    - 2_obesity_clinic/54_nobmi_IL24.obesity_clinic
    - 2_obesity_clinic/55_nobmi_IL13.obesity_clinic
    - 2_obesity_clinic/56_nobmi_ARTN.obesity_clinic
    - 2_obesity_clinic/57_nobmi_MMP10.obesity_clinic
    - 2_obesity_clinic/58_nobmi_IL10.obesity_clinic
    - 2_obesity_clinic/59_nobmi_TNF.obesity_clinic
    - 2_obesity_clinic/5_nobmi_GDNF.obesity_clinic
    - 2_obesity_clinic/60_nobmi_CCL23.obesity_clinic
    - 2_obesity_clinic/61_nobmi_CD5.obesity_clinic
    - 2_obesity_clinic/62_nobmi_CCL3_inf.obesity_clinic
    - 2_obesity_clinic/63_nobmi_Flt3L.obesity_clinic
    - 2_obesity_clinic/64_nobmi_CXCL6.obesity_clinic
    - 2_obesity_clinic/65_nobmi_CXCL10.obesity_clinic
    - 2_obesity_clinic/66_nobmi_X4EBP1.obesity_clinic
    - 2_obesity_clinic/67_nobmi_IL20.obesity_clinic
    - 2_obesity_clinic/68_nobmi_SIRT2.obesity_clinic
    - 2_obesity_clinic/69_nobmi_CCL28.obesity_clinic
    - 2_obesity_clinic/6_nobmi_CDCP1.obesity_clinic
    - 2_obesity_clinic/70_nobmi_DNER.obesity_clinic
    - 2_obesity_clinic/71_nobmi_ENRAGE.obesity_clinic
    - 2_obesity_clinic/72_nobmi_CD40.obesity_clinic
    - 2_obesity_clinic/73_nobmi_IL33.obesity_clinic
    - 2_obesity_clinic/74_nobmi_IFNg.obesity_clinic
    - 2_obesity_clinic/75_nobmi_FGF19.obesity_clinic
    - 2_obesity_clinic/76_nobmi_IL4.obesity_clinic
    - 2_obesity_clinic/77_nobmi_LIF.obesity_clinic
    - 2_obesity_clinic/78_nobmi_NRTN.obesity_clinic
    - 2_obesity_clinic/79_nobmi_MCP2.obesity_clinic
    - 2_obesity_clinic/7_nobmi_CD244.obesity_clinic
    - 2_obesity_clinic/80_nobmi_CASP8.obesity_clinic
    - 2_obesity_clinic/81_nobmi_CCL25.obesity_clinic
    - 2_obesity_clinic/82_nobmi_CX3CL1.obesity_clinic
    - 2_obesity_clinic/83_nobmi_TNFRSF9.obesity_clinic
    - 2_obesity_clinic/84_nobmi_NT3.obesity_clinic
    - 2_obesity_clinic/85_nobmi_TWEAK.obesity_clinic
    - 2_obesity_clinic/86_nobmi_CCL20.obesity_clinic
    - 2_obesity_clinic/87_nobmi_ST1A1.obesity_clinic
    - 2_obesity_clinic/88_nobmi_STAMBP.obesity_clinic
    - 2_obesity_clinic/89_nobmi_IL5.obesity_clinic
    - 2_obesity_clinic/8_nobmi_IL7.obesity_clinic
    - 2_obesity_clinic/90_nobmi_ADA.obesity_clinic
    - 2_obesity_clinic/91_nobmi_TNFB.obesity_clinic
    - 2_obesity_clinic/92_nobmi_CSF1.obesity_clinic
    - 2_obesity_clinic/93_nobmi_BMP6.obesity_clinic
    - 2_obesity_clinic/94_nobmi_ANGPT1.obesity_clinic
    - 2_obesity_clinic/95_nobmi_ADM.obesity_clinic
    - 2_obesity_clinic/96_nobmi_CD40L.obesity_clinic
    - 2_obesity_clinic/97_nobmi_SLAMF7.obesity_clinic
    - 2_obesity_clinic/98_nobmi_PGF.obesity_clinic
    - 2_obesity_clinic/99_nobmi_ADAMTS13.obesity_clinic
    - 2_obesity_clinic/9_nobmi_OPG.obesity_clinic
nobmi_proteins:
    - 100_nobmi_BOC
    - 101_nobmi_IL4RA
    - 102_nobmi_SRC
    - 103_nobmi_IL1ra
    - 104_nobmi_IL6
    - 105_nobmi_TNFRSF10A
    - 106_nobmi_STK4
    - 107_nobmi_IDUA
    - 108_nobmi_TNFRSF11A
    - 109_nobmi_PAR1
    - 10_nobmi_LAP_TGFb1
    - 110_nobmi_TRAILR2
    - 111_nobmi_PRSS27
    - 112_nobmi_TIE2
    - 113_nobmi_TF
    - 114_nobmi_IL1RL2
    - 115_nobmi_PDGF_subunit_B
    - 116_nobmi_IL27
    - 117_nobmi_IL17D
    - 118_nobmi_CXCL1
    - 119_nobmi_LOX1
    - 11_nobmi_uPA
    - 120_nobmi_Gal9
    - 121_nobmi_GIF
    - 122_nobmi_SCF
    - 123_nobmi_IL18
    - 124_nobmi_FGF21
    - 125_nobmi_PIgR
    - 126_nobmi_RAGE
    - 127_nobmi_SOD2
    - 128_nobmi_CTRC
    - 129_nobmi_FGF23
    - 12_nobmi_IL6_inf
    - 130_nobmi_SPON2
    - 131_nobmi_GH
    - 132_nobmi_FS
    - 133_nobmi_GLO1
    - 134_nobmi_CD84
    - 135_nobmi_PAPPA
    - 136_nobmi_SERPINA12
    - 137_nobmi_REN
    - 138_nobmi_DECR1
    - 139_nobmi_MERTK
    - 13_nobmi_IL17C
    - 140_nobmi_KIM1
    - 141_nobmi_THBS2
    - 142_nobmi_TM
    - 143_nobmi_VSIG2
    - 144_nobmi_AMBP
    - 145_nobmi_PRELP
    - 146_nobmi_HO1
    - 147_nobmi_XCL1
    - 148_nobmi_IL16
    - 149_nobmi_SORT1
    - 14_nobmi_MCP1
    - 150_nobmi_CEACAM8
    - 151_nobmi_PTX3
    - 152_nobmi_PSGL1
    - 153_nobmi_CCL17
    - 154_nobmi_CCL3
    - 155_nobmi_MMP7
    - 156_nobmi_IgG_Fc_receptor_IIb
    - 157_nobmi_ITGB1BP2
    - 158_nobmi_DCN
    - 159_nobmi_Dkk1
    - 15_nobmi_IL17A
    - 160_nobmi_LPL
    - 161_nobmi_PRSS8
    - 162_nobmi_AGRP
    - 163_nobmi_HBEGF
    - 164_nobmi_GDF2
    - 165_nobmi_FABP2
    - 166_nobmi_THPO
    - 167_nobmi_MARCO
    - 168_nobmi_GT
    - 169_nobmi_BNP
    - 16_nobmi_CXCL11
    - 170_nobmi_MMP12
    - 171_nobmi_ACE2
    - 172_nobmi_PDL2
    - 173_nobmi_CTSL1
    - 174_nobmi_hOSCAR
    - 175_nobmi_TNFRSF13B
    - 176_nobmi_TGM2
    - 177_nobmi_LEP
    - 178_nobmi_CA5A
    - 179_nobmi_HSP_27
    - 17_nobmi_AXIN1
    - 180_nobmi_CD4
    - 181_nobmi_NEMO
    - 182_nobmi_VEGFD
    - 183_nobmi_PARP1
    - 184_nobmi_HAOX1
    - 18_nobmi_TRAIL
    - 19_nobmi_IL20RA
    - 1_nobmi_IL8
    - 20_nobmi_CXCL9
    - 21_nobmi_CST5
    - 22_nobmi_IL2RB
    - 23_nobmi_IL1_a
    - 24_nobmi_OSM
    - 25_nobmi_IL2
    - 26_nobmi_CXCL1_inf
    - 27_nobmi_TSLP
    - 28_nobmi_CCL4
    - 29_nobmi_CD6
    - 2_nobmi_VEGFA
    - 30_nobmi_SCF_inf
    - 31_nobmi_IL18_inf
    - 32_nobmi_SLAMF1
    - 33_nobmi_TGFa
    - 34_nobmi_MCP4
    - 35_nobmi_CCL11
    - 36_nobmi_TNFSF14
    - 37_nobmi_FGF23_inf
    - 38_nobmi_IL10RA
    - 39_nobmi_FGF5
    - 3_nobmi_CD8A
    - 40_nobmi_MMP1
    - 41_nobmi_LIFR
    - 42_nobmi_FGF21_inf
    - 43_nobmi_CCL19
    - 44_nobmi_IL15RA
    - 45_nobmi_IL10RB
    - 46_nobmi_IL22_RA1
    - 47_nobmi_IL18R1
    - 48_nobmi_PDL1
    - 49_nobmi_BetaNGF
    - 4_nobmi_MCP3
    - 50_nobmi_CXCL5
    - 51_nobmi_TRANCE
    - 52_nobmi_HGF
    - 53_nobmi_IL12B
    - 54_nobmi_IL24
    - 55_nobmi_IL13
    - 56_nobmi_ARTN
    - 57_nobmi_MMP10
    - 58_nobmi_IL10
    - 59_nobmi_TNF
    - 5_nobmi_GDNF
    - 60_nobmi_CCL23
    - 61_nobmi_CD5
    - 62_nobmi_CCL3_inf
    - 63_nobmi_Flt3L
    - 64_nobmi_CXCL6
    - 65_nobmi_CXCL10
    - 66_nobmi_X4EBP1
    - 67_nobmi_IL20
    - 68_nobmi_SIRT2
    - 69_nobmi_CCL28
    - 6_nobmi_CDCP1
    - 70_nobmi_DNER
    - 71_nobmi_ENRAGE
    - 72_nobmi_CD40
    - 73_nobmi_IL33
    - 74_nobmi_IFNg
    - 75_nobmi_FGF19
    - 76_nobmi_IL4
    - 77_nobmi_LIF
    - 78_nobmi_NRTN
    - 79_nobmi_MCP2
    - 7_nobmi_CD244
    - 80_nobmi_CASP8
    - 81_nobmi_CCL25
    - 82_nobmi_CX3CL1
    - 83_nobmi_TNFRSF9
    - 84_nobmi_NT3
    - 85_nobmi_TWEAK
    - 86_nobmi_CCL20
    - 87_nobmi_ST1A1
    - 88_nobmi_STAMBP
    - 89_nobmi_IL5
    - 8_nobmi_IL7
    - 90_nobmi_ADA
    - 91_nobmi_TNFB
    - 92_nobmi_CSF1
    - 93_nobmi_BMP6
    - 94_nobmi_ANGPT1
    - 95_nobmi_ADM
    - 96_nobmi_CD40L
    - 97_nobmi_SLAMF7
    - 98_nobmi_PGF
    - 99_nobmi_ADAMTS13
    - 9_nobmi_OPG
