cohort_folder:
    - 1_population
samples:
    - 1_population/100_nobmi_BOC.population
    - 1_population/101_nobmi_IL4RA.population
    - 1_population/102_nobmi_SRC.population
    - 1_population/103_nobmi_IL1ra.population
    - 1_population/104_nobmi_IL6.population
    - 1_population/105_nobmi_TNFRSF10A.population
    - 1_population/106_nobmi_STK4.population
    - 1_population/107_nobmi_IDUA.population
    - 1_population/108_nobmi_TNFRSF11A.population
    - 1_population/109_nobmi_PAR1.population
    - 1_population/10_nobmi_LAP_TGFb1.population
    - 1_population/110_nobmi_TRAILR2.population
    - 1_population/111_nobmi_PRSS27.population
    - 1_population/112_nobmi_TIE2.population
    - 1_population/113_nobmi_TF.population
    - 1_population/114_nobmi_IL1RL2.population
    - 1_population/115_nobmi_PDGF_subunit_B.population
    - 1_population/116_nobmi_IL27.population
    - 1_population/117_nobmi_IL17D.population
    - 1_population/118_nobmi_CXCL1.population
    - 1_population/119_nobmi_LOX1.population
    - 1_population/11_nobmi_uPA.population
    - 1_population/120_nobmi_Gal9.population
    - 1_population/121_nobmi_GIF.population
    - 1_population/122_nobmi_SCF.population
    - 1_population/123_nobmi_IL18.population
    - 1_population/124_nobmi_FGF21.population
    - 1_population/125_nobmi_PIgR.population
    - 1_population/126_nobmi_RAGE.population
    - 1_population/127_nobmi_SOD2.population
    - 1_population/128_nobmi_CTRC.population
    - 1_population/129_nobmi_FGF23.population
    - 1_population/12_nobmi_IL6_inf.population
    - 1_population/130_nobmi_SPON2.population
    - 1_population/131_nobmi_GH.population
    - 1_population/132_nobmi_FS.population
    - 1_population/133_nobmi_GLO1.population
    - 1_population/134_nobmi_CD84.population
    - 1_population/135_nobmi_PAPPA.population
    - 1_population/136_nobmi_SERPINA12.population
    - 1_population/137_nobmi_REN.population
    - 1_population/138_nobmi_DECR1.population
    - 1_population/139_nobmi_MERTK.population
    - 1_population/13_nobmi_IL17C.population
    - 1_population/140_nobmi_KIM1.population
    - 1_population/141_nobmi_THBS2.population
    - 1_population/142_nobmi_TM.population
    - 1_population/143_nobmi_VSIG2.population
    - 1_population/144_nobmi_AMBP.population
    - 1_population/145_nobmi_PRELP.population
    - 1_population/146_nobmi_HO1.population
    - 1_population/147_nobmi_XCL1.population
    - 1_population/148_nobmi_IL16.population
    - 1_population/149_nobmi_SORT1.population
    - 1_population/14_nobmi_MCP1.population
    - 1_population/150_nobmi_CEACAM8.population
    - 1_population/151_nobmi_PTX3.population
    - 1_population/152_nobmi_PSGL1.population
    - 1_population/153_nobmi_CCL17.population
    - 1_population/154_nobmi_CCL3.population
    - 1_population/155_nobmi_MMP7.population
    - 1_population/156_nobmi_IgG_Fc_receptor_IIb.population
    - 1_population/157_nobmi_ITGB1BP2.population
    - 1_population/158_nobmi_DCN.population
    - 1_population/159_nobmi_Dkk1.population
    - 1_population/15_nobmi_IL17A.population
    - 1_population/160_nobmi_LPL.population
    - 1_population/161_nobmi_PRSS8.population
    - 1_population/162_nobmi_AGRP.population
    - 1_population/163_nobmi_HBEGF.population
    - 1_population/164_nobmi_GDF2.population
    - 1_population/165_nobmi_FABP2.population
    - 1_population/166_nobmi_THPO.population
    - 1_population/167_nobmi_MARCO.population
    - 1_population/168_nobmi_GT.population
    - 1_population/169_nobmi_BNP.population
    - 1_population/16_nobmi_CXCL11.population
    - 1_population/170_nobmi_MMP12.population
    - 1_population/171_nobmi_ACE2.population
    - 1_population/172_nobmi_PDL2.population
    - 1_population/173_nobmi_CTSL1.population
    - 1_population/174_nobmi_hOSCAR.population
    - 1_population/175_nobmi_TNFRSF13B.population
    - 1_population/176_nobmi_TGM2.population
    - 1_population/177_nobmi_LEP.population
    - 1_population/178_nobmi_CA5A.population
    - 1_population/179_nobmi_HSP_27.population
    - 1_population/17_nobmi_AXIN1.population
    - 1_population/180_nobmi_CD4.population
    - 1_population/181_nobmi_NEMO.population
    - 1_population/182_nobmi_VEGFD.population
    - 1_population/183_nobmi_PARP1.population
    - 1_population/184_nobmi_HAOX1.population
    - 1_population/18_nobmi_TRAIL.population
    - 1_population/19_nobmi_IL20RA.population
    - 1_population/1_nobmi_IL8.population
    - 1_population/20_nobmi_CXCL9.population
    - 1_population/21_nobmi_CST5.population
    - 1_population/22_nobmi_IL2RB.population
    - 1_population/23_nobmi_IL1_a.population
    - 1_population/24_nobmi_OSM.population
    - 1_population/25_nobmi_IL2.population
    - 1_population/26_nobmi_CXCL1_inf.population
    - 1_population/27_nobmi_TSLP.population
    - 1_population/28_nobmi_CCL4.population
    - 1_population/29_nobmi_CD6.population
    - 1_population/2_nobmi_VEGFA.population
    - 1_population/30_nobmi_SCF_inf.population
    - 1_population/31_nobmi_IL18_inf.population
    - 1_population/32_nobmi_SLAMF1.population
    - 1_population/33_nobmi_TGFa.population
    - 1_population/34_nobmi_MCP4.population
    - 1_population/35_nobmi_CCL11.population
    - 1_population/36_nobmi_TNFSF14.population
    - 1_population/37_nobmi_FGF23_inf.population
    - 1_population/38_nobmi_IL10RA.population
    - 1_population/39_nobmi_FGF5.population
    - 1_population/3_nobmi_CD8A.population
    - 1_population/40_nobmi_MMP1.population
    - 1_population/41_nobmi_LIFR.population
    - 1_population/42_nobmi_FGF21_inf.population
    - 1_population/43_nobmi_CCL19.population
    - 1_population/44_nobmi_IL15RA.population
    - 1_population/45_nobmi_IL10RB.population
    - 1_population/46_nobmi_IL22_RA1.population
    - 1_population/47_nobmi_IL18R1.population
    - 1_population/48_nobmi_PDL1.population
    - 1_population/49_nobmi_BetaNGF.population
    - 1_population/4_nobmi_MCP3.population
    - 1_population/50_nobmi_CXCL5.population
    - 1_population/51_nobmi_TRANCE.population
    - 1_population/52_nobmi_HGF.population
    - 1_population/53_nobmi_IL12B.population
    - 1_population/54_nobmi_IL24.population
    - 1_population/55_nobmi_IL13.population
    - 1_population/56_nobmi_ARTN.population
    - 1_population/57_nobmi_MMP10.population
    - 1_population/58_nobmi_IL10.population
    - 1_population/59_nobmi_TNF.population
    - 1_population/5_nobmi_GDNF.population
    - 1_population/60_nobmi_CCL23.population
    - 1_population/61_nobmi_CD5.population
    - 1_population/62_nobmi_CCL3_inf.population
    - 1_population/63_nobmi_Flt3L.population
    - 1_population/64_nobmi_CXCL6.population
    - 1_population/65_nobmi_CXCL10.population
    - 1_population/66_nobmi_X4EBP1.population
    - 1_population/67_nobmi_IL20.population
    - 1_population/68_nobmi_SIRT2.population
    - 1_population/69_nobmi_CCL28.population
    - 1_population/6_nobmi_CDCP1.population
    - 1_population/70_nobmi_DNER.population
    - 1_population/71_nobmi_ENRAGE.population
    - 1_population/72_nobmi_CD40.population
    - 1_population/73_nobmi_IL33.population
    - 1_population/74_nobmi_IFNg.population
    - 1_population/75_nobmi_FGF19.population
    - 1_population/76_nobmi_IL4.population
    - 1_population/77_nobmi_LIF.population
    - 1_population/78_nobmi_NRTN.population
    - 1_population/79_nobmi_MCP2.population
    - 1_population/7_nobmi_CD244.population
    - 1_population/80_nobmi_CASP8.population
    - 1_population/81_nobmi_CCL25.population
    - 1_population/82_nobmi_CX3CL1.population
    - 1_population/83_nobmi_TNFRSF9.population
    - 1_population/84_nobmi_NT3.population
    - 1_population/85_nobmi_TWEAK.population
    - 1_population/86_nobmi_CCL20.population
    - 1_population/87_nobmi_ST1A1.population
    - 1_population/88_nobmi_STAMBP.population
    - 1_population/89_nobmi_IL5.population
    - 1_population/8_nobmi_IL7.population
    - 1_population/90_nobmi_ADA.population
    - 1_population/91_nobmi_TNFB.population
    - 1_population/92_nobmi_CSF1.population
    - 1_population/93_nobmi_BMP6.population
    - 1_population/94_nobmi_ANGPT1.population
    - 1_population/95_nobmi_ADM.population
    - 1_population/96_nobmi_CD40L.population
    - 1_population/97_nobmi_SLAMF7.population
    - 1_population/98_nobmi_PGF.population
    - 1_population/99_nobmi_ADAMTS13.population
    - 1_population/9_nobmi_OPG.population
nobmi_proteins:
    - 100_nobmi_BOC
    - 101_nobmi_IL4RA
    - 102_nobmi_SRC
    - 103_nobmi_IL1ra
    - 104_nobmi_IL6
    - 105_nobmi_TNFRSF10A
    - 106_nobmi_STK4
    - 107_nobmi_IDUA
    - 108_nobmi_TNFRSF11A
    - 109_nobmi_PAR1
    - 10_nobmi_LAP_TGFb1
    - 110_nobmi_TRAILR2
    - 111_nobmi_PRSS27
    - 112_nobmi_TIE2
    - 113_nobmi_TF
    - 114_nobmi_IL1RL2
    - 115_nobmi_PDGF_subunit_B
    - 116_nobmi_IL27
    - 117_nobmi_IL17D
    - 118_nobmi_CXCL1
    - 119_nobmi_LOX1
    - 11_nobmi_uPA
    - 120_nobmi_Gal9
    - 121_nobmi_GIF
    - 122_nobmi_SCF
    - 123_nobmi_IL18
    - 124_nobmi_FGF21
    - 125_nobmi_PIgR
    - 126_nobmi_RAGE
    - 127_nobmi_SOD2
    - 128_nobmi_CTRC
    - 129_nobmi_FGF23
    - 12_nobmi_IL6_inf
    - 130_nobmi_SPON2
    - 131_nobmi_GH
    - 132_nobmi_FS
    - 133_nobmi_GLO1
    - 134_nobmi_CD84
    - 135_nobmi_PAPPA
    - 136_nobmi_SERPINA12
    - 137_nobmi_REN
    - 138_nobmi_DECR1
    - 139_nobmi_MERTK
    - 13_nobmi_IL17C
    - 140_nobmi_KIM1
    - 141_nobmi_THBS2
    - 142_nobmi_TM
    - 143_nobmi_VSIG2
    - 144_nobmi_AMBP
    - 145_nobmi_PRELP
    - 146_nobmi_HO1
    - 147_nobmi_XCL1
    - 148_nobmi_IL16
    - 149_nobmi_SORT1
    - 14_nobmi_MCP1
    - 150_nobmi_CEACAM8
    - 151_nobmi_PTX3
    - 152_nobmi_PSGL1
    - 153_nobmi_CCL17
    - 154_nobmi_CCL3
    - 155_nobmi_MMP7
    - 156_nobmi_IgG_Fc_receptor_IIb
    - 157_nobmi_ITGB1BP2
    - 158_nobmi_DCN
    - 159_nobmi_Dkk1
    - 15_nobmi_IL17A
    - 160_nobmi_LPL
    - 161_nobmi_PRSS8
    - 162_nobmi_AGRP
    - 163_nobmi_HBEGF
    - 164_nobmi_GDF2
    - 165_nobmi_FABP2
    - 166_nobmi_THPO
    - 167_nobmi_MARCO
    - 168_nobmi_GT
    - 169_nobmi_BNP
    - 16_nobmi_CXCL11
    - 170_nobmi_MMP12
    - 171_nobmi_ACE2
    - 172_nobmi_PDL2
    - 173_nobmi_CTSL1
    - 174_nobmi_hOSCAR
    - 175_nobmi_TNFRSF13B
    - 176_nobmi_TGM2
    - 177_nobmi_LEP
    - 178_nobmi_CA5A
    - 179_nobmi_HSP_27
    - 17_nobmi_AXIN1
    - 180_nobmi_CD4
    - 181_nobmi_NEMO
    - 182_nobmi_VEGFD
    - 183_nobmi_PARP1
    - 184_nobmi_HAOX1
    - 18_nobmi_TRAIL
    - 19_nobmi_IL20RA
    - 1_nobmi_IL8
    - 20_nobmi_CXCL9
    - 21_nobmi_CST5
    - 22_nobmi_IL2RB
    - 23_nobmi_IL1_a
    - 24_nobmi_OSM
    - 25_nobmi_IL2
    - 26_nobmi_CXCL1_inf
    - 27_nobmi_TSLP
    - 28_nobmi_CCL4
    - 29_nobmi_CD6
    - 2_nobmi_VEGFA
    - 30_nobmi_SCF_inf
    - 31_nobmi_IL18_inf
    - 32_nobmi_SLAMF1
    - 33_nobmi_TGFa
    - 34_nobmi_MCP4
    - 35_nobmi_CCL11
    - 36_nobmi_TNFSF14
    - 37_nobmi_FGF23_inf
    - 38_nobmi_IL10RA
    - 39_nobmi_FGF5
    - 3_nobmi_CD8A
    - 40_nobmi_MMP1
    - 41_nobmi_LIFR
    - 42_nobmi_FGF21_inf
    - 43_nobmi_CCL19
    - 44_nobmi_IL15RA
    - 45_nobmi_IL10RB
    - 46_nobmi_IL22_RA1
    - 47_nobmi_IL18R1
    - 48_nobmi_PDL1
    - 49_nobmi_BetaNGF
    - 4_nobmi_MCP3
    - 50_nobmi_CXCL5
    - 51_nobmi_TRANCE
    - 52_nobmi_HGF
    - 53_nobmi_IL12B
    - 54_nobmi_IL24
    - 55_nobmi_IL13
    - 56_nobmi_ARTN
    - 57_nobmi_MMP10
    - 58_nobmi_IL10
    - 59_nobmi_TNF
    - 5_nobmi_GDNF
    - 60_nobmi_CCL23
    - 61_nobmi_CD5
    - 62_nobmi_CCL3_inf
    - 63_nobmi_Flt3L
    - 64_nobmi_CXCL6
    - 65_nobmi_CXCL10
    - 66_nobmi_X4EBP1
    - 67_nobmi_IL20
    - 68_nobmi_SIRT2
    - 69_nobmi_CCL28
    - 6_nobmi_CDCP1
    - 70_nobmi_DNER
    - 71_nobmi_ENRAGE
    - 72_nobmi_CD40
    - 73_nobmi_IL33
    - 74_nobmi_IFNg
    - 75_nobmi_FGF19
    - 76_nobmi_IL4
    - 77_nobmi_LIF
    - 78_nobmi_NRTN
    - 79_nobmi_MCP2
    - 7_nobmi_CD244
    - 80_nobmi_CASP8
    - 81_nobmi_CCL25
    - 82_nobmi_CX3CL1
    - 83_nobmi_TNFRSF9
    - 84_nobmi_NT3
    - 85_nobmi_TWEAK
    - 86_nobmi_CCL20
    - 87_nobmi_ST1A1
    - 88_nobmi_STAMBP
    - 89_nobmi_IL5
    - 8_nobmi_IL7
    - 90_nobmi_ADA
    - 91_nobmi_TNFB
    - 92_nobmi_CSF1
    - 93_nobmi_BMP6
    - 94_nobmi_ANGPT1
    - 95_nobmi_ADM
    - 96_nobmi_CD40L
    - 97_nobmi_SLAMF7
    - 98_nobmi_PGF
    - 99_nobmi_ADAMTS13
    - 9_nobmi_OPG
